## --------------------------- ## 
#  farol_addons                #
## --------------------------- ## 
addons/console_path_parser:
    node_frequency: 5
    topics:
        subscribers: 
            Mission_String: "/mblack0/addons/Mission_String"
            state: "/mblack0/nav/filter/state"
            flag: "/mblack0/Flag"
        publishers:
            Path_Section: "/mblack0/addons/path_section"
            Formation: "/mblack0/addons/formation"
            biased_formation: "/mblack0/addons/biased_formation"
            WPRef: "/mblack0/addons/WPRef"
            DepthRef: "/mblack0/ref/depth"
            AltRef: "/mblack0/ref/altitude"
            FullMission: "/mblack0/addons/full_mission"
        services:
            reset_path: "/mblack0/ResetPath"
            arc2d_path: "/mblack0/SpawnArc2DPath"
            line_path: "/mblack0/SpawnLinePath"
            pf_start: "/mblack0/PFStart"
            pf_stop: "/mblack0/PFStop"
            set_speed: "/mblack0/SetConstVdVehicle"

addons/console_server:
    PORT: 7080
    topics:
      services:
          wp_standard: "/mblack0/controls/send_wp_standard"
          wp_loose: "/mblack0/controls/send_wp_loose"
          wp_heading: "/mblack0/controls/send_wp_heading"
      console:
          waypoint: "wp_standard"
    
addons/aggregator:
    pub_rate: 2.0

addons/remote_controller:
    node_frequency: 10 #Hz
    topics:
        publishers:
            # Linear velocity inner-loops
            surge: "/mblack0/ref/surge"
            sway: "/mblack0/ref/sway"
            heave: "/mblack0/ref/heave"

            # Angular speed references
            yaw_rate: "/mblack0/ref/yaw_rate"

            # Orientation references
            yaw: "/mblack0/ref/yaw"

            # Depth references
            depth: "/mblack0/ref/depth"

        subscribers:
            state: "/mblack0/nav/filter/state"

## --------------------------- ## 
#  farol_sim                   #
## --------------------------- ## 
## dynamic model
sim/auv_sim:
    frame_id: "mblack0"
    node_frequency: 100 # (Hz)
    topics:
        subscribers:
            thrusters: "/mblack0/thrusters/rpm_command"
        publishers:
            odometry: "/mblack0/sim/dynamics/position"
        services:
            start_pause: "/mblack0/sim/pause_start"

## sensor simulator
sim/sensors:
    node_frequency: 10
    topics:
        subscribers: 
            position: "/mblack0/sim/dynamics/position"
        publishers: 
            position: "/mblack0/measurement/position"
            velocity: "/mblack0/measurement/velocity"
            orientation: "/mblack0/measurement/orientation"
            gnss: "/mblack0/sensors/gnss"
            range: "/mblack0/sensors/range"
            state: "/mblack0/sim/model/state"
    services:
      enable_dvl: "/mblack0/sim/enable_dvl"
      enable_altimeter: "/mblack0/sim/enable_altimeter"

## --------------------------- ## 
#  farol_nav                   #
## --------------------------- ## 
nav/filter:
    node_frequency: 10      # ROS node rate
    topics:
        subscribers:
            reset: "/mblack0/nav/filter/reset"
            position: "/mblack0/measurement/position"
            velocity: "/mblack0/measurement/velocity"
            orientation: "/mblack0/measurement/orientation"
        publishers:
            state: "/mblack0/nav/filter/state"
            currents: "/mblack0/nav/filter/currents"
    topics_dr:
       velocity: "/mblack0/measurement/velocity"
       orientation: "/mblack0/measurement/orientation"
       true_state: "/mblack0/nav/filter/state"
       flag: "/mblack0/Flag"
       dead_reckoning: "/mblack0/nav/filter/state_dr"
       dead_reckoning_console: "/mblack0/State_dr"
    services_dr:
       reset_filter_dr: "/mblack0/nav/reset_filter_dr"

nav/gnss2utm:
    node_frequency: 10
    topics:
        subscribers:
            gnss: "/mblack0/sensors/gnss" 
        publishers: 
            position: "/mblack0/measurement/position"
            ground_truth: "/mblack0/State_gt"
    services:
        enable_gps: "/mblack0/sensor/enable_gps"

nav/gnss2utmoutlier:
    node_frequency: 10
    topics:
        subscribers:
            gnss: "/mblack0/sensors/gnss" 
        publishers: 
            position: "/mblack0/measurement/position"
    services:
        enable_gps_outlier: "/mblack0/sensor/fake/enable_gps_outlier"
        enable_usbl_delay: "/mblack0/sensor/fake/enable_usbl_delay"

nav/usbl2pos:
    node_frequency: 10
    topics:
        subscribers:
            usbl_fix: "/mblack0/sensors/usbl_fix"
            acomms_state: "/mblack0/acomms/nav/filter/state"
            state: "/mblack0/nav/filter/state"
        publishers:
            position: "/mblack0/measurement/position"
            console_state_usbl_estimation: "/mblack0/State_usbl_est"
            state_usbl_estimation: "/mblack0/nav/filter/usbl_est"

nav/auvstate2mstate:
    node_frequency: 10
    topics:
        subscribers:
            state: "/mblack0/nav/filter/state"
            gnss: "/mblack0/sensors/gnss"
            inside_pressure_filter: "/mblack0/drivers/inside_pressure_filter/data"
            inside_pressure_rate: "/mblack0/drivers/inside_pressure_filter/data_dot"
        publishers:  
            console_state: "/mblack0/State"

## --------------------------- ## 
#  farol_control               #
## --------------------------- ## 
controls/static_thruster_allocation:
    topics:
        subscribers:
            thrust_body_request: "/mblack0/thrust_body_request"
        publishers:
            thrusters: "/mblack0/thrusters/rpm_command"

controls/inner_loops_pid:
    node_frequency: 10.0 
    topics:
        subscribers:
            yaw: "/mblack0/ref/yaw"
            pitch: "/mblack0/ref/pitch"
            roll: "/mblack0/ref/roll"
            yaw_rate: "/mblack0/ref/yaw_rate"
            pich_rate: "/mblack0/ref/pitch_rate"
            roll_rate: "/mblack0/ref/roll_rate"
            surge: "/mblack0/ref/surge"
            sway: "/mblack0/ref/sway"
            heave: "/mblack0/ref/heave"
            depth: "/mblack0/ref/depth"
            altitude: "/mblack0/ref/altitude"
            altitude_safety: "/mblack0/ref/altitude_safety"
            depth_safety: "/mblack0/ref/depth_safety"
            state: "/mblack0/nav/filter/state"
            force_bypass: "/mblack0/force_bypass"
        publishers:
            thrust_body_request: "/mblack0/thrust_body_request"
        services: 
            change_ff_gains: "/mblack0/inner_forces/change_ff_gains"
            change_inner_gains: "/mblack0/inner_forces/change_inner_gains"
            change_inner_limits: "/mblack0/inner_forces/change_inner_limits"

controls/waypoint:
    node_frequency: 10.0
    topics:
        publishers:
            yaw_ref: "/mblack0/ref/yaw"
            yaw_rate_ref: "/mblack0/ref/yaw_rate"
            u_ref: "/mblack0/ref/surge"
            v_ref: "/mblack0/ref/sway"
            flag: "/mblack0/Flag"
        subscribers:
            flag: "/mblack0/Flag"
            state: "/mblack0/nav/filter/state"
        services:
            wp_standard: "/mblack0/controls/send_wp_standard"
            wp_loose: "/mblack0/controls/send_wp_loose"
            wp_heading: "/mblack0/controls/send_wp_heading"

controls/path_following:
    node_frequency: 10.0
    flag: "/mblack0/Flag"
    topics:
        subscribers:
            state: "/mblack0/nav/filter/state"
            path: "/mblack0/PathData"
            vc: "/mblack0/PF/vc"
        publishers:
            surge: "/mblack0/ref/surge"
            sway: "/mblack0/ref/sway"
            heave: "/mblack0/ref/heave"
            roll: "/mblack0/ref/roll"
            roll_rate: "/mblack0/ref/roll_rate"
            pitch: "/mblack0/ref/pitch"
            pitch_rate: "/mblack0/ref/pitch_rate"
            yaw: "/mblack0/ref/yaw"
            yaw_rate: "/mblack0/ref/yaw_rate"
    
            # Publishers for the virtual target
            rabbit: "/mblack0/Gamma"
            
            # Observer for the currents
            observer:
                x: "/mblack0/current/x"
                y: "/mblack0/current/y"

            # Publish info for plots
            pfollowing_debug: "/mblack0/pfollowing/debug"
        
        services:
            # Service names to start and stop the path following algorithm
            start_pf: "/mblack0/PFStart"
            stop_pf: "/mblack0/PFStop"
            updates_gains_pf: "/mblack0/PFUpdateGains"
            reset_vt_pf: "/mblack0/ResetVT"
    
            # Service names to switch the path following algorithm
            relative_heading_pf: "/mblack0/PFSetRelativeHeading"
            marcelo_pf: "/mblack0/PFSetMarcelo"
            aguiar_pf: "/mblack0/PFSetAguiar"
            brevik_pf: "/mblack0/PFSetBrevik"
            fossen_pf: "/mblack0/PFSetFossen"
            romulo_pf: "/mblack0/PFSetRomulo"
            lapierre_pf: "/mblack0/PFSetLapierre"
            pramod_pf: "/mblack0/PFSetPramod"
            samson_pf: "/mblack0/PFSetSamson"
            relative_heading_pf: "/mblack0/PFSetRelativeHeading"
            # Service names related to the path
            reset_path: "/mblack0/ResetPath"
            set_path_mode: "/mblack0/SetMode"
            # Service names related to the waypoint
            wp_standard: "/mblack0/controls/send_wp_standard"

controls/vehicle_stabilizer:
  topics:
    publishers:
      surge: "/mblack0/ref/surge"
      sway: "/mblack0/ref/heave"
      heave: "/mblack0/ref/heave"

      roll_rate: "/mblack0/ref/roll_rate"
      pitch_rate: "/mblack0/ref/pitch_rate"
      yaw_rate: "/mblack0/ref/yaw_rate"

      roll: "/mblack0/ref/roll"
      pitch: "/mblack0/ref/pitch"
      yaw: "/mblack0/ref/yaw"

      depth: "/mblack0/ref/depth"
      altitude: "/mblack0/ref/altitude"
   
### Cooperative control law
cooperative/cpf_control:
    node_frequency: 10
    topics:
        publishers: 
            vc: "/mblack0/PF/vc"
            cpf_server_input: "/mblack0/Internal/Gamma"
        subscribers:
            internal_gamma: "/mblack0/PathData"
            external_gamma: "/mblack0/External/Gamma"
        services:
        # Service names to start and stop the path following algorithm
            start_cpf: "/mblack0/CPFStart"
            stop_cpf: "/mblack0/CPFStop"
            change_topology: "/mblack0/CPFChangeTopology"

cooperative/cpf_wifi_server:
    broadcast_port: 2808
    node_frequency: 10
    topics:
      subscribers:
        internal_gamma: "/mblack0/Internal/Gamma"
      publishers:
        cpf_gamma: "/mblack0/External/Gamma"
        
cooperative/cpf_wifi_client:
    broadcast_port: 2808
    node_frequency: 10
    topics:
      subscribers:
        internal_gamma: "/mblack0/Internal/Gamma"
      publishers:
        cpf_gamma: "/mblack0/External/Gamma"

## --------------------------- ## 
#  farol_planning              #
## --------------------------- ##
planning/dsor_paths:
    node_frequency: 10.0
    frame_id: "Path_frame"
    topics:
        subscribers:
            gamma: "/mblack0/Gamma"
            vehicle_state: "/mblack0/nav/filter/state"
        publishers:
            path_data: "/mblack0/PathData"
            virtual_target_state: "/mblack0/Virtual/State"
        # Services for constructing a path
        services:
            reset_path: "/mblack0/ResetPath"
            set_mode: "/mblack0/SetMode"
            arc2d_path: "/mblack0/SpawnArc2DPath"
            bernoulli_path: "/mblack0/SpawnBernoulliPath"
            circle2d_path: "/mblack0/SpawnCircle2DPath"
            line_path: "/mblack0/SpawnLinePath"
            speed:
                const_rabbit_speed: "/mblack0/SetConstVdRabbit"
                const_vehicle_speed: "/mblack0/SetConstVdVehicle"

## --------------------------- ## 
#  farol_comms                #
## --------------------------- ## 
acomms/pinger:
    topics:
        publishers:
            modem_send: "/mblack0/acomms/modem/send"
            meas_usbl_fix: "/mblack0/sensors/usbl_fix"
            trigger_serialization: "/mblack0/acomms/scheme/trigger_serialization"
            deserialize: "/mblack0/acomms/scheme/payload_to_deserialize"
        subscribers:
            enable: "/mblack0/acomms/scheme/enable"
            modem_recv: "/mblack0/acomms/modem/recv"
            payload: "/mblack0/acomms/serializer/payload_to_transmit"

acomms/replier:
    topics:
        publishers:
            modem_send: "/mblack0/acomms/modem/send"
            meas_usbl_fix: "/mblack0/sensors/usbl_fix"
            trigger_serialization: "/mblack0/acomms/scheme/trigger_serialization"
            deserialize: "/mblack0/acomms/scheme/payload_to_deserialize"
        subscribers:
            modem_recv: "/mblack0/acomms/modem/recv"
            payload: "/mblack0/acomms/serializer/payload_to_transmit"

acomms/data_serializer:
    topics:
        publishers:
            to_modem: "/mblack0/acomms/serializer/payload_to_transmit"
        subscribers:
            from_modem: "/mblack0/acomms/scheme/payload_to_deserialize"
            trigger: "/mblack0/acomms/scheme/trigger_serialization"
        
acomms/dmac2farol:
    topics:
        publishers:
            farol_fix: "/mblack0/sensors/usbl_fix"
        subscribers:
            dmac_fix: "/mblack0/acomms/modem/measurement/usbl_fix"
            state: "/mblack0/nav/filter/state"

acomms/gnss2state:
    topics:
        subscribers:
            gnss: "/mblack0/acomms/nav/filter/gnss"
        publishers:
            state: "/mblack0/acomms/nav/filter/state"
            utmzone: "/mblack0/state/utmzone"

acomms/pos2sim_modem:
    topics/subscribers/position: "/mblack0/sim/dynamics/position"
