addons/console_server:
    PORT: 23518

cooperative/cpf_wifi_server:
    broadcast_port: 24518

cooperative/cpf_wifi_client:
    broadcast_port: 24518

cpp_counter/CppCounterNode:
  topics:
    subscribers:
      pause: "/mblack0/cpp_counter/pause"
    publishers:
      count: "/mblack0/cpp_counter/count"

python_counter/python_counterNode:
  topics:
    subscribers:
      pause: "/mblack0/python_counter/pause"
    publishers:
      count: "/mblack0/python_counter/count"
